apiVersion: v1
kind: Service
metadata:
  name: service-persist-type
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: persist-type
  ports:
    - name: http-persist-type
      protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: http
