apiVersion: v1
kind: Service
metadata:
  name: service-type-query
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: type-query
  ports:
    - name: http-type-query
      protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: http
