CREATE TABLE public."user" (
    id uuid NOT NULL,
    provider character varying(32) NOT NULL,
    account character varying(64) NOT NULL,
    name character varying(16) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_modified_at timestamp(6) with time zone NOT NULL,
    last_login_at timestamp(6) with time zone,
    state character varying(12) DEFAULT 'ACTIVATED'::character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.workspace (
    id uuid NOT NULL,
    name character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by uuid NOT NULL,
    last_modified_at timestamp(6) with time zone NOT NULL,
    last_modified_by uuid NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS type (
    workspace UUID NOT NULL,
    id UUID NOT NULL,
    name character varying(64),
    parent character varying(64),
    created_at timestamp(6) with time zone NOT NULL,
    created_by uuid NOT NULL,
    effective_at timestamp(6) with time zone NOT NULL,
    expire_at timestamp(6) with time zone NOT NULL,
    primitive boolean NOT NULL,
    version TEXT,
    description text NOT NULL,
    x smallint DEFAULT 0 NOT NULL,
    y smallint DEFAULT 0 NOT NULL,
    width smallint DEFAULT 0 NOT NULL,
    height smallint DEFAULT 0 NOT NULL,
    last boolean DEFAULT true NOT NULL,
    PRIMARY KEY (workspace, id)
) PARTITION BY HASH (workspace);

CREATE TABLE public.attribute (
    workspace uuid NOT NULL,
    type uuid NOT NULL,
    name character varying(32) NOT NULL,
    attribute_type jsonb NOT NULL,
    "order" smallint NOT NULL,
    nullable boolean NOT NULL,
    description character varying(255),
    PRIMARY KEY (workspace, type, name),
    CONSTRAINT attribute_type_check CHECK (
        (attribute_type->>'base_type') IN ('Value', 'Array', 'Map', 'File', 'Document')
    )
);
CREATE TABLE public.layout (
    workspace uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by uuid NOT NULL,
    effective_at timestamp(6) with time zone NOT NULL,
    expire_at timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (workspace, id)
);

CREATE TABLE public.layout_type (
    workspace uuid NOT NULL,
    layout uuid NOT NULL,
    type character varying(64) NOT NULL,
    version character varying(64) NOT NULL,
    x smallint NOT NULL,
    y smallint NOT NULL,
    width smallint NOT NULL,
    height smallint NOT NULL,
    PRIMARY KEY (workspace, layout, type, version)
);

CREATE TABLE public.layout_attribute (
    workspace uuid NOT NULL,
    layout uuid NOT NULL,
    type character varying(255) NOT NULL,
    version character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (workspace, layout, type, version, name)
);

CREATE TABLE public."group" (
    workspace uuid NOT NULL,
    name character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by uuid NOT NULL,
    last_modified_at timestamp(6) with time zone NOT NULL,
    last_modified_by uuid NOT NULL,
    PRIMARY KEY (workspace, name)
);

CREATE TABLE public.group_member (
    workspace uuid NOT NULL,
    "group" character varying(32) NOT NULL,
    member uuid NOT NULL,
    PRIMARY KEY (workspace, "group", member)
);

CREATE TABLE public.group_role (
    workspace uuid NOT NULL,
    "group" character varying(32) NOT NULL,
    role uuid NOT NULL,
    PRIMARY KEY (workspace, "group", role)
);

CREATE TABLE public.role (
    id uuid NOT NULL,
    name character varying(16) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by uuid NOT NULL,
    last_modified_at timestamp(6) with time zone NOT NULL,
    last_modified_by uuid NOT NULL
);

CREATE TABLE type_partition_00 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 0);
CREATE TABLE type_partition_01 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 1);
CREATE TABLE type_partition_02 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 2);
CREATE TABLE type_partition_03 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 3);
CREATE TABLE type_partition_04 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 4);
CREATE TABLE type_partition_05 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 5);
CREATE TABLE type_partition_06 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 6);
CREATE TABLE type_partition_07 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 7);
CREATE TABLE type_partition_08 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 8);
CREATE TABLE type_partition_09 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 9);
CREATE TABLE type_partition_10 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 10);
CREATE TABLE type_partition_11 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 11);
CREATE TABLE type_partition_12 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 12);
CREATE TABLE type_partition_13 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 13);
CREATE TABLE type_partition_14 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 14);
CREATE TABLE type_partition_15 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 15);
CREATE TABLE type_partition_16 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 16);
CREATE TABLE type_partition_17 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 17);
CREATE TABLE type_partition_18 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 18);
CREATE TABLE type_partition_19 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 19);
CREATE TABLE type_partition_20 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 20);
CREATE TABLE type_partition_21 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 21);
CREATE TABLE type_partition_22 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 22);
CREATE TABLE type_partition_23 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 23);
CREATE TABLE type_partition_24 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 24);
CREATE TABLE type_partition_25 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 25);
CREATE TABLE type_partition_26 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 26);
CREATE TABLE type_partition_27 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 27);
CREATE TABLE type_partition_28 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 28);
CREATE TABLE type_partition_29 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 29);
CREATE TABLE type_partition_30 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 30);
CREATE TABLE type_partition_31 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 31);
CREATE TABLE type_partition_32 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 32);
CREATE TABLE type_partition_33 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 33);
CREATE TABLE type_partition_34 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 34);
CREATE TABLE type_partition_35 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 35);
CREATE TABLE type_partition_36 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 36);
CREATE TABLE type_partition_37 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 37);
CREATE TABLE type_partition_38 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 38);
CREATE TABLE type_partition_39 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 39);
CREATE TABLE type_partition_40 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 40);
CREATE TABLE type_partition_41 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 41);
CREATE TABLE type_partition_42 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 42);
CREATE TABLE type_partition_43 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 43);
CREATE TABLE type_partition_44 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 44);
CREATE TABLE type_partition_45 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 45);
CREATE TABLE type_partition_46 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 46);
CREATE TABLE type_partition_47 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 47);
CREATE TABLE type_partition_48 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 48);
CREATE TABLE type_partition_49 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 49);
CREATE TABLE type_partition_50 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 50);
CREATE TABLE type_partition_51 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 51);
CREATE TABLE type_partition_52 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 52);
CREATE TABLE type_partition_53 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 53);
CREATE TABLE type_partition_54 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 54);
CREATE TABLE type_partition_55 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 55);
CREATE TABLE type_partition_56 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 56);
CREATE TABLE type_partition_57 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 57);
CREATE TABLE type_partition_58 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 58);
CREATE TABLE type_partition_59 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 59);
CREATE TABLE type_partition_60 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 60);
CREATE TABLE type_partition_61 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 61);
CREATE TABLE type_partition_62 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 62);
CREATE TABLE type_partition_63 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 63);
CREATE TABLE type_partition_64 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 64);
CREATE TABLE type_partition_65 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 65);
CREATE TABLE type_partition_66 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 66);
CREATE TABLE type_partition_67 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 67);
CREATE TABLE type_partition_68 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 68);
CREATE TABLE type_partition_69 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 69);
CREATE TABLE type_partition_70 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 70);
CREATE TABLE type_partition_71 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 71);
CREATE TABLE type_partition_72 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 72);
CREATE TABLE type_partition_73 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 73);
CREATE TABLE type_partition_74 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 74);
CREATE TABLE type_partition_75 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 75);
CREATE TABLE type_partition_76 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 76);
CREATE TABLE type_partition_77 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 77);
CREATE TABLE type_partition_78 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 78);
CREATE TABLE type_partition_79 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 79);
CREATE TABLE type_partition_80 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 80);
CREATE TABLE type_partition_81 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 81);
CREATE TABLE type_partition_82 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 82);
CREATE TABLE type_partition_83 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 83);
CREATE TABLE type_partition_84 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 84);
CREATE TABLE type_partition_85 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 85);
CREATE TABLE type_partition_86 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 86);
CREATE TABLE type_partition_87 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 87);
CREATE TABLE type_partition_88 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 88);
CREATE TABLE type_partition_89 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 89);
CREATE TABLE type_partition_90 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 90);
CREATE TABLE type_partition_91 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 91);
CREATE TABLE type_partition_92 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 92);
CREATE TABLE type_partition_93 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 93);
CREATE TABLE type_partition_94 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 94);
CREATE TABLE type_partition_95 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 95);
CREATE TABLE type_partition_96 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 96);
CREATE TABLE type_partition_97 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 97);
CREATE TABLE type_partition_98 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 98);
CREATE TABLE type_partition_99 PARTITION OF type FOR VALUES WITH (MODULUS 100, REMAINDER 99);