spring:
  application:
    name: search-document
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:handbook}
    username: ${DB_USER:handbook}
    password: ${DB_PASSWORD:handbook}
