kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
data:
  kafka.yaml: |
    spring:
      cloud:
        stream:
          kafka:
            binder:
              brokers: kafka-kafka-bootstrap:9092
              auto-add-partitions: true
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: event-topic-publisher
  namespace: {{ .Release.Namespace }}
data:
  event-topic-publisher.yaml: |
    spring:
      cloud:
        function:
          definition: event
        stream:
          bindings:
            event-out-0:
              destination: event