apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: event
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: kafka
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: validation-task
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: kafka
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
