apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket
  namespace: {{ .Release.Namespace }}
spec:
  bucketName: {{ .Values.bucket.name }}
  storageClassName: ocs-storagecluster-ceph-rgw
  additionalConfig:
    maxSize: {{ .Values.bucket.maxSize }}
