apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: handbook
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - gateway-https
  hosts:
    - {{ .Values.host }}
  http:
      - match:
          - uri:
              prefix: /types
            method: GET
        route:
          - destination:
              host: search-type
              port:
                number: 80
      - match:
          - uri:
              prefix: /types
            method:
              - PUT
              - POST
              - DELETE
              - PATCH
        route:
          - destination:
              host: persist
              port:
                number: 80
    - match:
        - uri:
            exact: /type
      rewrite:
        uri: /{{ .Values.bucket.name }}/static/type.html
      route:
        - destination:
            host: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /css
      rewrite:
        uri: /{{ .Values.bucket.name }}/static/css
      route:
        - destination:
            host: >-
              rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /js
      rewrite:
        uri: /{{ .Values.bucket.name }}/static/js
      route:
        - destination:
            host: >-
              rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
            port:
              number: 80
