spring:
  application:
    name: persist-workspace
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:handbook}
    username: ${DB_USER:handbook}
    password: ${DB_PASSWORD:handbook}
  cloud:
    stream:
      bindings:
        workspace-out-0:
          destination: workspace-events
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
