apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: handbook
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: handbook-test
            bucket: handbook-test
            database: 192.168.1.211
            host: handbook.sayaya.cloud
            mode: test
            stage: test
          - name: handbook
            bucket: handbook
            database: 192.168.1.210
            host: handbook.sayaya.dev
            mode: ''
            stage: prod
  template:
    metadata:
      annotations:
        kargo.akuity.io/authorized-stage: handbook-operator:handbook-{{`{{ stage }}`}}
      name: '{{`{{ name }}`}}'
    spec:
      project: handbook
      destination:
        namespace: '{{`{{ name }}`}}'
        server: 'https://kubernetes.default.svc'
      sources:
        - path: charts/handbook
          repoURL: 'https://github.com/sayaya1090/handbook.git'
          targetRevision: HEAD
          helm:
            parameters:
              - name: host
                value: '{{`{{ host }}`}}'
              - name: mode
                value: '{{`{{ mode }}`}}'
              - name: bucket.name
                value: '{{`{{ bucket }}`}}'
              - name: database.ip
                value: '{{`{{ database }}`}}'
              - forceString: true
                name: gateway.image.name
                value: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/gateway'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true