kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-role-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-role-{{ .Release.Namespace }}

