apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: handbook-test
  namespace: {{ .Release.Namespace }}
  annotations:
     kargo.akuity.io/color: amber
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: handbook
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: compose-output
          as: gateway-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/gateway") }}` }}
        - uses: compose-output
          as: login-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/login") }}` }}
        - uses: compose-output
          as: persist-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/persist") }}` }}
        - uses: compose-output
          as: search-user-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/search-user") }}` }}
        - uses: compose-output
          as: persist-user-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/persist-user") }}` }}
        - uses: compose-output
          as: search-workspace-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/search-workspace") }}` }}
        - uses: compose-output
          as: persist-workspace-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/persist-workspace") }}` }}
        - uses: compose-output
          as: search-type-image
          config:
            img: {{ `${{ imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/search-type") }}` }}
        - uses: argocd-update
          as: sync
          config:
            apps:
              - name: handbook-test
                sources:
                  - helm:
                      images:
                        - key: gateway.image.tag
                          value: {{ `${{ outputs['gateway-image'].img.tag }}@${{ outputs['gateway-image'].img.digest }}` }}
                        - key: login.image.tag
                          value: {{ `${{ outputs['login-image'].img.tag }}@${{ outputs['login-image'].img.digest }}` }}
                        - key: persist.image.tag
                          value: {{ `${{ outputs['persist-image'].img.tag }}@${{ outputs['persist-image'].img.digest }}` }}
                        - key: search-user.image.tag
                          value: {{ `${{ outputs['search-user-image'].img.tag }}@${{ outputs['search-user-image'].img.digest }}` }}
                        - key: persist-user.image.tag
                          value: {{ `${{ outputs['persist-user-image'].img.tag }}@${{ outputs['persist-user-image'].img.digest }}` }}
                        - key: search-workspace.image.tag
                          value: {{ `${{ outputs['search-workspace-image'].img.tag }}@${{ outputs['search-workspace-image'].img.digest }}` }}
                        - key: persist-workspace.image.tag
                          value: {{ `${{ outputs['persist-workspace-image'].img.tag }}@${{ outputs['persist-workspace-image'].img.digest }}` }}
                        - key: search-type.image.tag
                          value: {{ `${{ outputs['search-type-image'].img.tag }}@${{ outputs['search-type-image'].img.digest }}` }}
                    repoURL: https://github.com/sayaya1090/handbook.git
  verification:
    analysisTemplates:
    - name: gateway-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: handbook-prod
  namespace: {{ .Release.Namespace }}
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: handbook
      sources:
        direct: false
        stages:
          - handbook-test
  promotionTemplate:
    spec:
      steps:
        - uses: http
          as: add-tag
          config:
              url: https://api.github.com/repos/sayaya1090/handbook/dispatches
              method: POST
              headers:
                - name: Authorization
                  value: token {{`${{ secrets.github.token }}`}}
                - name: Accept
                  value: application/vnd.github.v3+json
              body: |
                {{`${{ quote({
                  "event_type": "release",
                  "client_payload": {
                    "ctx": ctx,
                    "images": [
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/gateway"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/login"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/persist"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/search-user"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/persist-user"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/search-workspace"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/persist-workspace"),
                      imageFrom("image-registry.openshift-image-registry.svc:5000/handbook-operator/search-type")
                    ],"commit": commitFrom("https://github.com/sayaya1090/handbook.git")
                  }
                }) }}`}}
              successExpression: response.status == 204
