apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: persist
  namespace: {{ .Release.Namespace }}
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: Lexical
        insecureSkipTLSVerify: true
        repoURL: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/persist'
        strictSemvers: true

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: search-type
  namespace: {{ .Release.Namespace }}
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        discoveryLimit: 20
        imageSelectionStrategy: Lexical
        insecureSkipTLSVerify: true
        repoURL: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/search-type'
        strictSemvers: true