apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: handbook
  namespace: {{ .Release.Namespace }}
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        insecureSkipTLSVerify: true
        repoURL: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/gateway'
        strictSemvers: true
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        insecureSkipTLSVerify: true
        repoURL: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/persist'
        strictSemvers: true
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        insecureSkipTLSVerify: true
        repoURL: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/search-type'
        strictSemvers: true
    - git:
        repoURL: https://github.com/sayaya1090/handbook.git
        branch: main
        includePaths:
          - gateway
          - persist
          - search-type
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 5
        strictSemvers: true
