kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arc-role-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - actions.github.com
    resources:
      - '*'
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arc-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: arc
    namespace: github-actions-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-role-{{ .Release.Namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc
  namespace: {{ .Release.Namespace }}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: handbook-arc-image-builder
subjects:
  - kind: ServiceAccount
    name: arc
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-builder'
