apiVersion: v1
kind: Service
metadata:
  name: service-workspace-command
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: workspace-command
  ports:
    - name: http-workspace-command
      protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: http
