{{- if .Values.database.backup.schedule }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-backup
  namespace: {{ .Release.Namespace }}
spec:
  backupOwnerReference: self
  cluster:
    name: postgresql
  schedule: {{ .Values.database.backup.schedule | quote }}
{{- end }}