image:
  name: image-registry.openshift-image-registry.svc:5000/handbook/document-query
  tag: 7cce32a
color: "brick"

stage:
  name: ""
  color: ""
  prev: ""

jvmBackend:
  fragments:
    - observability
    - authentication
    - postgresql
    - kafka
  extraEnv:
    - name: SPRING_ELASTICSEARCH_URIS
      value: "elasticsearch:9200"
