apiVersion: v1
kind: Service
metadata:
  name: service-login
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: login
  ports:
    - name: http-login
      protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: http
