annotations:
  charts.openshift.io/name: search-workspace
apiVersion: v2
kubeVersion: '>= 1.20.0-0'
name: search-workspace
version: 0.1.0
description: Search workspace (read side + menu supplier) service for handbook application
dependencies:
  - name: handbook-lib
    version: 0.1.0
    repository: file://../../handbook-lib
