apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.cluster.name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version | quote }}
    metadataVersion: {{ .Values.kafka.metadataVersion | quote }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      default.replication.factor: {{ .Values.kafka.config.replicationFactor }}
      min.insync.replicas: {{ .Values.kafka.config.minInSyncReplicas }}
      offsets.topic.replication.factor: {{ .Values.kafka.config.replicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.replicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.minInSyncReplicas }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        metadata:
          labels:
            istio.io/dataplane-mode: none
