spring:
  application:
    name: event-broadcaster
  cloud:
    stream:
      bindings:
        event-in-0:
          destination: handbook-events
          group: event-broadcaster
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
