{{- if not .Values.stage.prev }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: document-ui
  namespace: handbook
  annotations:
    kargo.akuity.io/color: {{ .Values.color }}
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    - git:
        repoURL: https://github.com/sayaya1090/handbook.git
        commitSelectionStrategy: Lexical
        allowTags: ^document-ui-
        strictSemvers: false
        discoveryLimit: 5
{{- end }}
