image:
  name: image-registry.openshift-image-registry.svc:5000/handbook/document-command
  tag: 5e42398
color: "red"

stage:
  name: ""
  color: ""
  prev: ""

jvmBackend:
  fragments:
    - observability
    - authentication
    - postgresql
    - kafka
