apiVersion: v1
kind: Service
metadata:
  name: service-gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http-gateway
      protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: http
