apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: "20"
    requests.cpu: "12"
    requests.memory: "8Gi"
    limits.cpu: "18"
    limits.memory: "16Gi"
