apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: handbook
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - gateway-https
  hosts:
    - {{ .Values.host }}
  http:
    - match:
        - uri:
            regex: ^/menus
          method:
            exact: GET
      route:
        - destination:
            host: service-gateway
            port:
              number: 80
    - match:
        - uri:
            regex: ^/workspace/[0-9a-fA-F-]{36}/(types|layouts)
          method:
            exact: GET
      route:
        - destination:
            host: search-type
            port:
              number: 80
    - match:
        - uri:
            regex: ^/workspace/[0-9a-fA-F-]{36}/(types|layouts)
          method:
            regex: ^(PUT|POST|DELETE|PATCH)$
      route:
        - destination:
            host: persist-type
            port:
              number: 80
    - match:
        - uri:
            prefix: /login/
        - uri:
            prefix: /oauth2/
      route:
        - destination:
            host: login
            port:
              number: 80
    - match:
        - uri:
            regex: ^/workspace
          method:
            exact: GET
      route:
        - destination:
            host: search-workspace
            port:
              number: 80
    - match:
        - uri:
            regex: ^/workspace
          method:
            regex: ^(PUT|POST|DELETE|PATCH)$
      route:
        - destination:
            host: persist-workspace
            port:
              number: 80
    - match:
        - uri:
            regex: ^/user
          method:
            exact: GET
      route:
        - destination:
            host: search-user
            port:
              number: 80
    - match:
        - uri:
            regex: ^/user
          method:
            regex: ^(PUT|POST|DELETE|PATCH)$
      route:
        - destination:
            host: persist-user
            port:
              number: 80
    - match:
        - uri:
            prefix: /css
      rewrite:
        uri: /{{ .Values.bucket.name }}/static/css
      route:
        - destination:
            host: >-
              rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /js
      rewrite:
        uri: /{{ .Values.bucket.name }}/static/js
      route:
        - destination:
            host: >-
              rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /{{ .Values.bucket.name }}/static/shell.html
      route:
        - destination:
            host: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local
            port:
              number: 80