apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    istio: gateway
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.host }}
  to:
    kind: Service
    name: gateway
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
  wildcardPolicy: None