name: 어시스턴트 모듈 배포
on:
  push:
    paths:
      - assistant/**
      - activity/**
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/_jvm-deploy.yaml
    with:
      submodule: assistant
    secrets: inherit
