name: 도메인 모듈 테스트
on:
  push:
    branches-ignore:
      - main
    paths:
      - document/**
      - schema/**
      - workspace/**
      - event/**
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
    strategy:
      matrix:
        module: [document, schema, workspace, event]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Test
        run: ./gradlew ${{ matrix.module }}:koverXmlReport
      - name: Report
        uses: ./.github/actions/coverage-summary
        with:
          module-name: ${{ matrix.module }}
          good-threshold: 80
          warn-threshold: 50
