name: 도메인 모듈 테스트
on:
  push:
    branches-ignore:
      - main
    paths:
      - domain/**
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
      SUBMODULE: domain
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Test
        run: gradle $SUBMODULE:koverXmlReport
      - name: Report
        uses: ./.github/actions/coverage-summary
        with:
          module-name: ${{ env.SUBMODULE }}
          good-threshold: 80
          warn-threshold: 50
