name: 로그인 UI 모듈 배포
on:
  push:
    paths:
      - login-ui/**
  workflow_dispatch:
jobs:
  test-and-deploy:
    runs-on: handbook-operator
    env:
      SUBMODULE: login-ui
      GITHUB_USERNAME: ${{ secrets._GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.13
      - name: Build & Test
        run: gradle $SUBMODULE:build
      - name: Unpack
        run: |
          mkdir -p static/js
          unzip -o $SUBMODULE/build/libs/*.war "**/*.js" "**/*.css" -d static
          mv static/login static/js/login
          mv static/logout static/js/logout
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ github.ref == 'refs/heads/main' && secrets.AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID_CANDIDATE }}
          AWS_SECRET_ACCESS_KEY: ${{ github.ref == 'refs/heads/main' && secrets.AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY_CANDIDATE }}
          AWS_DEFAULT_REGION: null
          S3_BUCKET: ${{ github.ref == 'refs/heads/main' && 'handbook' || 'handbook-test' }}
          S3_ENDPOINT: https://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc/
          DESTINATION: static
        run: |
          echo "GIT_REF_NAME=$GITHUB_REF_NAME"
          echo "BUCKET=$S3_BUCKET"
          echo "aws s3 sync --endpoint-url $S3_ENDPOINT static s3://$S3_BUCKET/$DESTINATION --acl public-read --no-verify-ssl"
          aws s3 sync --endpoint-url $S3_ENDPOINT static s3://$S3_BUCKET/$DESTINATION --acl public-read --no-verify-ssl
