name: 로그인 UI 모듈 빌드
on:
  push:
    paths:
      - login-ui/**
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/_frontend-deploy.yaml
    with:
      submodule: login-ui
    secrets: inherit
