name: 문서 영속화 모듈 배포
on:
  push:
    paths:
      - persist-document/**
      - activity/**
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/_jvm-deploy.yaml
    with:
      submodule: persist-document
    secrets: inherit
