name: 타입 영속화 모듈 배포
on:
  push:
    paths:
      - persist-type/**
      - activity/**
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/_jvm-deploy.yaml
    with:
      submodule: persist-type
    secrets: inherit
