name: 워크스페이스 영속화 모듈 배포
on:
  push:
    paths:
      - persist-workspace/**
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/_jvm-deploy.yaml
    with:
      submodule: persist-workspace
    secrets: inherit
