name: 타입 검색 모듈 배포
on:
  push:
    paths:
      - search-type/**
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/_jvm-deploy.yaml
    with:
      submodule: search-type
    secrets: inherit
