name: 쉘 UI 모듈 빌드
on:
  push:
    paths:
      - shell-ui/**
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/_frontend-deploy.yaml
    with:
      submodule: shell-ui
    secrets: inherit
