name: 워크스페이스 UI 모듈 빌드
on:
  push:
    paths:
      - workspace-ui/**
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/_frontend-deploy.yaml
    with:
      submodule: workspace-ui
    secrets: inherit
